import { Resend } from "resend";

const resend = new Resend(
  process.env.RESEND_API_KEY
);

const TEST_EMAIL =
  process.env.RESEND_TO_EMAIL ||
  "inamuafridi300@gmail.com";

const FROM_EMAIL =
  process.env.RESEND_FROM_EMAIL ||
  "Luis Caparrós Website <onboarding@resend.dev>";

const EMAIL_TEST_MODE =
  String(process.env.EMAIL_TEST_MODE).toLowerCase() === "true";


function escapeHtml(value = "") {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}


function validEmail(email = "") {
  return /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(
    email.trim()
  );
}


function contactTemplate({
  name,
  email,
  subject,
  message,
}) {
  const safeName = escapeHtml(name);
  const safeEmail = escapeHtml(email);
  const safeSubject = escapeHtml(
    subject || "No subject"
  );

  const safeMessage = escapeHtml(
    message
  ).replace(/\n/g, "<br>");

  return `
<!doctype html>
<html>
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>Luis Caparrós Contact</title>
</head>

<body
style="
margin:0;
padding:30px;
background:#f4f0e3;
font-family:Georgia,'Times New Roman',serif;
color:#16211c;
"
>

<div
style="
max-width:700px;
margin:0 auto;
background:#faf8f0;
border:1px solid #dcd3b8;
"
>

<div
style="
padding:35px;
text-align:center;
border-bottom:1px solid #dcd3b8;
"
>

<div
style="
font-family:Arial,sans-serif;
font-size:11px;
letter-spacing:3px;
color:#8b7651;
font-weight:bold;
margin-bottom:12px;
"
>
WEBSITE CONTACT
</div>

<h1
style="
margin:0;
font-size:34px;
letter-spacing:3px;
"
>
LUIS CAPARRÓS
</h1>

<p
style="
margin:12px 0 0;
font-family:Arial,sans-serif;
font-size:12px;
letter-spacing:2px;
color:#8b7651;
text-transform:uppercase;
"
>
New Message Received
</p>

</div>


<div style="padding:30px 35px 15px;">

<p
style="
margin:0;
font-size:18px;
line-height:1.7;
"
>
A new message has been submitted through the
<strong>Luis Caparrós</strong> website.
</p>

</div>


<div
style="
margin:20px 35px;
border:1px solid #ddd5c0;
background:#f6f2e7;
"
>

<div
style="
padding:18px 20px;
border-bottom:1px solid #ddd5c0;
"
>

<div
style="
font-family:Arial,sans-serif;
font-size:10px;
letter-spacing:2px;
color:#8b7651;
font-weight:bold;
text-transform:uppercase;
margin-bottom:7px;
"
>
Name
</div>

<div style="font-size:18px;">
${safeName}
</div>

</div>


<div
style="
padding:18px 20px;
border-bottom:1px solid #ddd5c0;
"
>

<div
style="
font-family:Arial,sans-serif;
font-size:10px;
letter-spacing:2px;
color:#8b7651;
font-weight:bold;
text-transform:uppercase;
margin-bottom:7px;
"
>
Email
</div>

<div
style="
font-family:Arial,sans-serif;
font-size:15px;
"
>
${safeEmail}
</div>

</div>


<div style="padding:18px 20px;">

<div
style="
font-family:Arial,sans-serif;
font-size:10px;
letter-spacing:2px;
color:#8b7651;
font-weight:bold;
text-transform:uppercase;
margin-bottom:7px;
"
>
Subject
</div>

<div style="font-size:17px;">
${safeSubject}
</div>

</div>

</div>


<div style="padding:10px 35px 35px;">

<div
style="
font-family:Arial,sans-serif;
font-size:10px;
letter-spacing:2px;
color:#8b7651;
font-weight:bold;
text-transform:uppercase;
margin-bottom:12px;
"
>
Message
</div>

<div
style="
background:#fff;
border-left:4px solid #8b7651;
padding:22px;
font-size:17px;
line-height:1.8;
"
>
${safeMessage}
</div>

</div>


<div
style="
padding:25px 35px;
border-top:1px solid #dcd3b8;
text-align:center;
background:#f2eee2;
"
>

<p
style="
margin:0;
font-family:Arial,sans-serif;
font-size:11px;
line-height:1.6;
color:#827b6c;
"
>
This email was automatically generated by the
Luis Caparrós website contact form.
</p>

</div>

</div>

</body>
</html>
`;
}


export default async function handler(
  req,
  res
) {
  if (req.method !== "POST") {
    return res.status(405).json({
      success: false,
      error: "Method not allowed.",
    });
  }

  try {
    if (!process.env.RESEND_API_KEY) {
      return res.status(500).json({
        success: false,
        error: "Email service is not configured.",
      });
    }

    const {
      name,
      email,
      subject,
      message,
    } = req.body || {};


    if (
      !name ||
      name.trim().length < 2
    ) {
      return res.status(400).json({
        success: false,
        error: "Please provide a valid name.",
      });
    }


    if (
      !email ||
      !validEmail(email)
    ) {
      return res.status(400).json({
        success: false,
        error: "Please provide a valid email.",
      });
    }


    if (
      !message ||
      message.trim().length < 10
    ) {
      return res.status(400).json({
        success: false,
        error: "Message is too short.",
      });
    }


    const recipient =
      EMAIL_TEST_MODE
        ? TEST_EMAIL
        : TEST_EMAIL;


    const { data, error } =
      await resend.emails.send({
        from: FROM_EMAIL,

        to: [recipient],

        replyTo: email.trim(),

        subject:
          `New message from ${name.trim()}`,

        html: contactTemplate({
          name: name.trim(),
          email: email.trim(),
          subject: subject?.trim() || "",
          message: message.trim(),
        }),
      });


    if (error) {
      console.error(
        "❌ Resend error:",
        error
      );

      return res.status(500).json({
        success: false,
        error:
          error.message ||
          "Email could not be sent.",
      });
    }


    console.log(
      "✅ Contact email sent:",
      data?.id
    );


    return res.status(200).json({
      success: true,
      message:
        "Your message has been sent successfully.",
      id: data?.id || null,
    });

  } catch (error) {
    console.error(
      "❌ Contact API error:",
      error
    );

    return res.status(500).json({
      success: false,
      error:
        error.message ||
        "Something went wrong while sending the message.",
    });
  }
}